### ISSUE TITLE
anthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}}

### ISSUE THREAD

**Issue by NasonZ** [Doriandarko/maestro#15]
I'm running into an `AuthenticationError` with a `401` status code indicating an "invalid x-api-key" when trying to interact with the Anthropic API using the Claude Opus model. 

**Trace:**
```
maestro$ python maestro-gpt.py
Please choose the orchestrator model (Claude Opus or GPT-4): Claude Opus 
Invalid choice. Please enter 'Claude Opus' or 'GPT-4': Claude Opus
Please enter your objective with or without a text file path: a playable version of pong where i use wasd to move                                                                         

Calling Orchestrator for your objective
Traceback (most recent call last):
  File "/home/taf/Dmyzer/search_engine/Prototypes/graphs/maestro/maestro-gpt.py", line 167, in <module>
    opus_result, file_content_for_subagent = opus_orchestrator(objective, file_content, previous_results)
  File "/home/taf/Dmyzer/search_engine/Prototypes/graphs/maestro/maestro-gpt.py", line 37, in opus_orchestrator
    opus_response = anthropic_client.messages.create(
  File "/home/taf/anaconda3/envs/llm_gym/lib/python3.10/site-packages/anthropic/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
  File "/home/taf/anaconda3/envs/llm_gym/lib/python3.10/site-packages/anthropic/resources/messages.py", line 678, in create
    return self._post(
  File "/home/taf/anaconda3/envs/llm_gym/lib/python3.10/site-packages/anthropic/_base_client.py", line 1232, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/taf/anaconda3/envs/llm_gym/lib/python3.10/site-packages/anthropic/_base_client.py", line 921, in request
    return self._request(
  File "/home/taf/anaconda3/envs/llm_gym/lib/python3.10/site-packages/anthropic/_base_client.py", line 1012, in _request
    raise self._make_status_error_from_response(err.response) from None
anthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}}
```
I made a fresh key and tested it with:

```
from anthropic import Anthropic

client = Anthropic(api_key="sk-xxxxx")

message = client.messages.create(
    model="claude-3-opus-20240229",
    max_tokens=1024,
    messages=[
        {"role": "user", "content": "Hello, Claude"}
    ]
)
print(message.content)

output:
[TextBlock(text='Hello! How can I assist you today?', type='text')]
```

I'm stumped at whats causing this error, any help would be appreciated.

**Comment by NasonZ** [comment]
Not sure what the cause was as its now working. Whatever it was I think it was on Anthropics side.

**Comment by Minocrisy** [comment]
I am geting this same error right now, whether I use gpt4o or anthropic. Did you ever figure out what was wrong? I am stumped too, but I am also a beginner.

**Comment by NasonZ** [comment]
I think the issue for me was that I had just made a new anthropic account so my api keys weren't live. Waited 15 or so minutes and then it worked. 

It's worth checking if your api-key is correct or trying a fresh one.

**Comment by Minocrisy** [comment]
thanks, tried all that a few times over, still same issue today. The thing is its happening with open ai as well. So it has to be a something I am missing or doing wrong. I have tried putting the api in the code, in and out of "", I tried setx in the conda env (for both LLM's API) so i can assume i am in the right directory. Anthropic is installed, the app runs, just no api
