### ISSUE TITLE
UnicodeEncodeError.

### ISSUE THREAD

**Issue by spocksbrain** [Doriandarko/maestro#35]
Have also been seeing the following repeatedly, which blows up the session.  Is there any way to increase the error handling to preserve the session?

Please note that the provided code and documentation serve as a starting point and may require further customization and refinement based on the specific requirements and constraints of the project.
Traceback (most recent call last):
  File "C:\Users\Spocksbrain\Documents\Code_Projects\maestro\maestro.py", line 303, in <module>
    file.write(exchange_log)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 6303-6305: character maps to <undefined>
PS C:\Users\Spocksbrain\Documents\Code_Projects\maestro>

**Comment by Felewin** [comment]
Had a lot of hype building up as it put together a multi page website with much back and forth only to get this error at the end after creating the folder!
