### ISSUE TITLE
Script starts but aborts with error: UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by dongle132** [Doriandarko/maestro#7]
I installed the python packages and added the API-Key but after asking for objective it shows this error:

Calling Opus for your objective
+- Opus Orchestrator ---------------------------------------------------------+
| Here is the next sub-task and prompt for the subagent:                      |
|                                                                             |
| Sub-task: Define the core functionalities needed for a Python GUI to        |
| control a rotating weapon platform (turret).                                |
|                                                                             |
| Prompt: Please list out the key features and functionalities that would be  |
| required in a Python-based graphical user interface to effectively monitor  |
| and control a rotating weapon platform (turret). Consider things like:      |
| - Displaying the current position/orientation of the turret                 |
| - Allowing the user to manually adjust the turret's position                |
| - Showing video feed from any cameras on the turret                         |
| - Statuses of the turret's subsystems (e.g. power, targeting sensors,       |
| weapon systems)                                                             |
| - Emergency stop button                                                     |
| - Firing controls and safety interlocks                                     |
| The goal is to define the core set of capabilities the GUI would need to    |
| include to enable an operator to use it to fully control the remote turret  |
| system. Please provide the list of required GUI functions and a brief       |
| description of each.                                                        |
+-------------------------Traceback (most recent call last):
  File "C:\Users\dongle\git\maestro\maestro\maestro.py", line 125, in <module>
    opus_result = opus_orchestrator(objective, previous_results)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dongle\git\maestro\maestro\maestro.py", line 33, in opus_orchestrator
    console.print(Panel(response_text, title=f"[bold green]Opus Orchestrator[/bold green]", title_align="left", border_style="green", subtitle="Sending task to Haiku \U0001f447"))
  File "C:\Users\dongle\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\console.py", line 1673, in print
    with self:
  File "C:\Users\dongle\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\console.py", line 865, in __exit__
    self._exit_buffer()
  File "C:\Users\dongle\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\console.py", line 823, in _exit_buffer
    self._check_buffer()
  File "C:\Users\dongle\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\console.py", line 2027, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\Users\dongle\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "C:\Users\dongle\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
  File "C:\Users\dongle\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
  File "C:\Users\dongle\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
**UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f447' in position 23: character maps to <undefined>**

`

**Comment by dongle132** [comment]
Fixed by removing 👇 from the script
